### ISSUE TITLE
MPAS-Analysis v0.6

### ISSUE THREAD

**Issue by xylar** [ACME-Climate/a-prime#14]
MPAS-Analysis has just been updated to v0.6.  It would be good to update a-prime accordingly, as there are many enhancements:
https://github.com/MPAS-Dev/MPAS-Analysis/releases/tag/v0.6
I'm happy to help wherever I can, e.g. with testing and with changes to the configuration.

Note: MPAS-Analysis now only works properly on 1 node, not on 1 node per task.  So various batch scripts will need to be changed accordingly.

**Comment by milenaveneziani** [comment]
addressed by #24
