### ISSUE TITLE
Create and test script to run on Anvil

### ISSUE THREAD

**Issue by milenaveneziani** [ACME-Climate/a-prime#2]
Note: @vanroekel now has a run_ANVIL that works for him, but it points to his own conda environment. Therefore, once it is decided that we should support Anvil as well, we need somebody to install an acme conda environment there.

**Comment by xylar** [comment]
I just saw this issue from June.  I have now installed acme-unified on Anvil and am happy to do what I can (script-writing or testing) to make sure A-Prime supports Anvil.

**Comment by milenaveneziani** [comment]
yes, thanks @xylar. Depending on how fast we move on the mpas-analysis side, we can either make a separate PR or bundle it together with the new mpas-analysis tag.

**Comment by milenaveneziani** [comment]
Addressed in #24 thanks to @vanroekel.
