### ISSUE TITLE
files lose permissions when licenses are added

### ISSUE THREAD

**Issue by xylar** [ACME-Climate/a-prime#21]
There's an issue with:
https://github.com/ACME-Climate/a-prime/blob/master/docs/_headers/license-prepend-missing.sh#L40

A temp file is created for prepending the license header but the permissions of the temp file aren't the same as for the original file.

I fixed this in MPAS-Analysis here:
https://github.com/MPAS-Dev/MPAS-Analysis/pull/160/files#diff-7d6a6be86295ac21a991d68806543d11R47

Something similar needs to be done in a-prime.  Note that this needs to happen in at least 4 places within the script (and perhaps elsewhere).

**Comment by milenaveneziani** [comment]
Addressed by #22.
