### ISSUE TITLE
OHC plots fail when not starting from simulation start year

### ISSUE THREAD

**Issue by sterlingbaldwin** [ACME-Climate/a-prime#28]
If a-prime is run on a time span not starting from year 1 of the simulation, none of the OHC plots will be generated. For example, if the simulation goes from years 0001 to 0100, and I run aprime on years 0051 to 0060, with only data from 0051 to 0060 (as well as all the required restart and streams files), the OHC plots will not be produced. This only happens when my input directory only contains 0051 to 0060 data, if I ran it on the same years but the 0001-0100 data was all in the directory it would work fine. This means there must be additional data requirements not listed in the script.

**Comment by milenaveneziani** [comment]
@sterlingbaldwin: the OHC analysis needs the first year of the simulation because it's a metric computed with the temperature anomalies calculated wrt the first year field. This is clearly documented in run_aprime.bash:
```
#       - mpas-o files:
#               mpaso.hist.am.timeSeriesStatsMonthly.*.nc (Note: since OHC
#                   anomalies are computed wrt the first year of the simulation,
#                   if OHC diagnostics is activated, the analysis will need the
#                   first full year of mpaso.hist.am.timeSeriesStatsMonthly.*.nc
#                   files, no matter what begin_yr_ts, end_yr_ts are. 
```

**Comment by sterlingbaldwin** [comment]
ah ok, so it should work if years 51-60 are the only files, if the first whole year is also present?

**Comment by milenaveneziani** [comment]
yes, exactly. That will work.
